name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.13.0-chrome96-ff94
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install UI Dependencies
        run: npm install
        working-directory: ./ui-tests

      - name: Run Cypress UI Tests
        run: npx cypress run
        working-directory: ./ui-tests

  api-tests:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.13.0-chrome96-ff94
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install API Dependencies
        run: npm install
        working-directory: ./api-tests

      - name: Run Cypress API Tests
        run: npx cypress run
        working-directory: ./api-tests
