name: Cypress UI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-ui-tests:
    runs-on: ubuntu-latest
    container:
      image: cypress/included:8.7.0
      options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
        working-directory: ./ui-tests

      - name: Run Cypress UI tests
        run: npm run test:cypress
        working-directory: ./ui-tests
