name: Full Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    container:
      image: cypress/included:8.7.0
      options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install UI dependencies
        run: npm install
        working-directory: ./ui-tests

      - name: Run Cypress UI tests
        run: npm run test:cypress
        working-directory: ./ui-tests

  api-tests:
    runs-on: ubuntu-latest
    container:
      image: node:14 # Using Node.js container, adjust the version as needed
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install API dependencies
        run: npm install
        working-directory: ./api-tests

      - name: Run API tests
        run: npm run test:api # Make sure this script is defined in your package.json
        working-directory: ./api-tests
